[build]
  publish = "web"
  functions = "netlify/functions"

[[edge_functions]]
  path = "/admin/*"
  function = "admin-auth"

[[edge_functions]]
  path = "/admin-login"
  function = "admin-auth"

[[edge_functions]]
  path = "/admin-logout"
  function = "admin-auth"
